name: CI

on:
  push:
    branches:
    - master
    - 'release/**'
  pull_request:
    branches:
    - master
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Configure JFrog Artifactory
        run: |
          echo "npmRegistryServer: ${{ secrets.JFROG_ARTIFACTORY_NPM_VIRTUAL_URL }}" >> .yarnrc.yml
          echo "npmAuthIdent: ${{ secrets.JFROG_ARTIFACTORY_DATA_PIPELINES_NPM_AUTH }}" >> .yarnrc.yml
          echo "npmAlwaysAuth: true" >> .yarnrc.yml

      - name: Install
        run: yarn install --immutable
      
      - name: Build
        run: yarn run build
      
      - name: Test
        run: yarn run test

      - name: Codacy Coverage upload
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/clover.xml
